os: linux
language: node_js
dist: xenial

jobs:
  allow_failures:
    - os: windows
  include:
    - stage: test
      name: Linux - test
      language: node_js
      os: linux
      node_js:
        - 17
      cache:
        yarn: true
      script: yarn test
    - stage: release
      language: node_js
      os: linux
      node_js:
        - 17
      branches:
        only:
          - master
      cache:
        yarn: true
      script: skip
      deploy:
        provider: script
        cleanup: true
        script: bash script/deploy.sh
