# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2

references:
  dependencies_cache_key: &dependencies_cache_key
    v1-dependencies-{{ checksum "package.json" }}
  dependencies_backup_cache_key: &dependencies_backup_cache_key
    v1-dependencies-
  run_tests: &run_tests
    steps:
      - checkout
      - restore_cache:
          keys:
            - *dependencies_cache_key
            - *dependencies_backup_cache_key
      - run: yarn install
      - save_cache:
          key: *dependencies_cache_key
          paths:
            - node_modules
      - run: yarn test

jobs:
  build:
    docker:
      - image: circleci/node:10
    <<: *run_tests
  release:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - *dependencies_cache_key
            - *dependencies_backup_cache_key
      - run: yarn install
      - save_cache:
          key: *dependencies_cache_key
          paths:
            - node_modules
      - run: sudo yarn global add semantic-release
      - run:
          name: prepublish
          command: yarn prepublishOnly
      - run: semantic-release

workflows:
  version: 2
  build:
    jobs:
      - build
      - release:
          requires:
            - build
